# refer to https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# MD004/ul-style - Unordered list style
MD004:
  style: "sublist"

# MD013/line-length - Line length
MD013:
  line_length: 200
  heading_line_length: 128
  code_block_line_length: 200
