upgrade: true
dep: dev,prod
reject:
- '@types/react'
- '@types/react-dom'
- '@simplewebauthn/*' # TODO 升级 4 → 5
- 'codemirror' # TODO 升级 5 → 6
- 'react' # 先不升级 18
- 'react-dom' # 先不升级 18
- 'stylelint' # 14 不行
- 'stylelint-config-standard'
- 'stylelint-order'